[project]
name = "ceu-dbt-assignment"
version = "1.0.0"
requires-python = "==3.13.*"
dependencies = [
    "dbt-autofix>=0.18.6",
    "dbt-core~=1.11.0",
    "dbt-snowflake~=1.11.0",
    "sqlfluff>=4.0.0",
    "sqlfluff-templater-dbt>=4.0.0",
]
